// Array de objetos representando plantas medicinais.
// Cada objeto possui as seguintes propriedades:
// - titulo: Nome comum e científico da planta (string), utiliza-se em itálico por tratar de nome científico;
// - descricao: Descrição das propriedades medicinais e usos populares (string);
// - link: Link para mais informações sobre a planta (string);

let dados = [
    {
        titulo: "Angico - <i>Anadenanthera colubrina</i> (Vell.) Brenan",
        descricao: "<p>O angico possui um rico histórico de uso na medicina popular. Suas diferentes partes, como a casca e as sementes, são ricas em compostos bioativos que conferem à planta diversas propriedades medicinais. A casca, por exemplo, é rica em taninos, substâncias com ação adstringente, anti-inflamatória e antimicrobiana, sendo utilizada para tratar problemas gastrointestinais, infecções e inflamações. Já as sementes, embora ricas em alcaloides psicoativos e com uso restrito, são utilizadas em rituais indígenas. É importante ressaltar que o uso do angico deve ser feito com cautela e sob orientação de um profissional de saúde, pois algumas de suas substâncias podem causar efeitos colaterais. O chá de casca de angico é uma das formas mais comuns de consumo, mas a planta também pode ser utilizada em tinturas e macerados. No entanto, o uso das sementes é restrito por lei devido ao seu potencial psicoativo.</p><p>Chá da casca</p><p>Ferve-se 1 litro de água e adiciona-se uma colher de sopa de casca seca. Abafe por 10 minutos. Coe o chá e adoce se desejar. Recomenda-se ingerir de 1 a 2 xícaras ao dia, entre as refeições.</p>",
        link: "https://floradobrasil.jbrj.gov.br/consulta/?grupo=6&familia=null&genero=Anadenanthera&especie=colubrina&autor=&nomeVernaculo=&nomeCompleto=&formaVida=null&substrato=null&ocorreBrasil=QUALQUER&ocorrencia=OCORRE&endemismo=TODOS&origem=TODOS&regiao=QUALQUER&ilhaOceanica=32767&estado=QUALQUER&domFitogeograficos=QUALQUER&vegetacao=TODOS&mostrarAte=SUBESP_VAR&opcoesBusca=TODOS_OS_NOMES&loginUsuario=Visitante&senhaUsuario=&contexto=consulta-publica&pagina=1#CondicaoTaxonCP",
    },
    {
        titulo: "Aroeira - <i>Astronium urundeuva</i> (M.Allemão) Engl.",
        descricao: "<p>A aroeira tem sido utilizada há séculos na fitoterapia. Suas folhas, cascas, frutos e resina possuem compostos que combatem inflamações, infecções e dores, além de auxiliar na cicatrização e na função renal. O chá de aroeira é a forma mais comum de consumo, mas a planta também pode ser utilizada em banhos, cataplasmas e óleos. Apesar de seus benefícios, é importante lembrar que a aroeira possui contraindicações e pode causar efeitos colaterais se utilizada de forma incorreta. Por isso, antes de iniciar qualquer tratamento com a aroeira, consulte um médico ou fitoterapeuta.</p> <p>Chá (casca ou folhas)</p> <p>Ferve-se 1 litro de água e adiciona-se cinco colheres de sopa de casca ou folhas secas. Abafe por 10 minutos. Coe o chá e adoce se desejar. Recomenda-se ingerir de 2 a 3 xícaras ao dia, entre as refeições.</p>",
        link: "https://floradobrasil.jbrj.gov.br/consulta/?grupo=6&familia=null&genero=Astronium&especie=urundeuva&autor=&nomeVernaculo=&nomeCompleto=&formaVida=null&substrato=null&ocorreBrasil=QUALQUER&ocorrencia=OCORRE&endemismo=TODOS&origem=TODOS&regiao=QUALQUER&ilhaOceanica=32767&estado=QUALQUER&domFitogeograficos=QUALQUER&vegetacao=TODOS&mostrarAte=SUBESP_VAR&opcoesBusca=TODOS_OS_NOMES&loginUsuario=Visitante&senhaUsuario=&contexto=consulta-publica&pagina=1#CondicaoTaxonCP",
    },
    {
        titulo: "Faveleira - <i>Cnidoscolus quercifolius</i> Pohl",
        descricao: "A faveleira, apesar de seus pelos urticantes, é uma planta medicinal rica em propriedades terapêuticas. Nativa da América do Sul, suas folhas e raízes são as partes mais utilizadas. Graças à presença de flavonoides, alcaloides e saponinas, a faveleira possui ação anti-inflamatória, analgésica, cicatrizante, diurética e purgativa. É utilizada popularmente para tratar inflamações, dores, problemas de pele, renais e intestinais. A planta pode ser usada em forma de chá, cataplasma ou banho de assento. No entanto, devido à presença de substâncias irritantes, seu uso deve ser feito com cautela e sob orientação médica, pois pode causar efeitos colaterais como irritação na pele e problemas gastrointestinais. Além disso, é contraindicada para gestantes, lactantes e pessoas com determinadas condições de saúde. Em resumo, a faveleira é uma planta medicinal com grande potencial, mas seu uso deve ser feito com responsabilidade e conhecimento.</p> <p>Chá (folhas ou raízes)</p> <p>Ferve-se 1 litro de água e adiciona-se cinco colheres de sopa de folhas ou raízes secas. Abafe por 10 minutos. Coe o chá e adoce se desejar. Recomenda-se ingerir de 2 a 3 xícaras ao dia, entre as refeições.</p>",
        link: "https://floradobrasil.jbrj.gov.br/consulta/?grupo=6&familia=null&genero=Cnidoscolus&especie=quercifolius&autor=&nomeVernaculo=&nomeCompleto=&formaVida=null&substrato=null&ocorreBrasil=QUALQUER&ocorrencia=OCORRE&endemismo=TODOS&origem=TODOS&regiao=QUALQUER&ilhaOceanica=32767&estado=QUALQUER&domFitogeograficos=QUALQUER&vegetacao=TODOS&mostrarAte=SUBESP_VAR&opcoesBusca=TODOS_OS_NOMES&loginUsuario=Visitante&senhaUsuario=&contexto=consulta-publica&pagina=1#CondicaoTaxonCP",
    },
    {
        titulo: "Mororó - <i>Bauhinia cheilantha</i> (Bong.) Steud.",
        descricao: "O mororó é amplamente utilizado na medicina popular devido às suas diversas propriedades terapêuticas. Suas folhas, casca e raízes são ricas em compostos bioativos como antioxidantes e flavonoides, que conferem à planta ações anti-inflamatória, antioxidante, antidiabética e hipocolesterolêmica. O chá de mororó é a forma mais comum de consumo, sendo utilizado para tratar inflamações, diabetes e colesterol alto. No entanto, é importante ressaltar que o uso do mororó deve ser feito com cautela e sob orientação de um profissional de saúde, pois pode causar efeitos colaterais e interagir com outros medicamentos. Apesar de seus benefícios, o mororó não substitui o tratamento médico convencional para doenças mais graves.</p><p>Chá ds folhas</p><p>Ferve-se 1 litro de água e adiciona-se cinco colheres de sopa de folhas secas. Abafe por 10 minutos. Coe o chá e adoce se desejar. Recomenda-se ingerir de 2 a 3 xícaras ao dia, entre as refeições.</p>",
        link: "https://floradobrasil.jbrj.gov.br/consulta/?grupo=6&familia=null&genero=Bauhinia&especie=cheilantha&autor=&nomeVernaculo=&nomeCompleto=&formaVida=null&substrato=null&ocorreBrasil=QUALQUER&ocorrencia=OCORRE&endemismo=TODOS&origem=TODOS&regiao=QUALQUER&ilhaOceanica=32767&estado=QUALQUER&domFitogeograficos=QUALQUER&vegetacao=TODOS&mostrarAte=SUBESP_VAR&opcoesBusca=TODOS_OS_NOMES&loginUsuario=Visitante&senhaUsuario=&contexto=consulta-publica&pagina=1#CondicaoTaxonCP",
    },
    {
        titulo: "Mulungu - <i>Erythrina velutina</i> Willd.",
        descricao: "O mulungu é amplamente utilizado na medicina popular por suas propriedades calmantes e sedativas. Suas flores, casca e raízes são as partes mais utilizadas devido à presença de compostos bioativos que atuam no sistema nervoso central. O mulungu é eficaz no tratamento da ansiedade, insônia e depressão, além de apresentar propriedades anti-inflamatórias e antiespasmódicas. As formas de uso mais comuns são o chá, a tintura e as cápsulas. No entanto, é importante ressaltar que o uso do mulungu deve ser feito com cautela e sob orientação médica, pois pode causar efeitos colaterais como sonolência e tontura, e interagir com outros medicamentos. Apesar de seus benefícios, o mulungu não substitui o tratamento médico convencional para doenças mais graves.</p><p>Chá da casca</p><p>Ferve-se 1 litro de água e adiciona-se cinco colheres de sopa de cascas secas. Abafe por 10 minutos. Coe o chá e adoce se desejar. Recomenda-se ingerir de 2 a 3 xícaras por dia, preferencialmente à noite, para auxiliar no sono.",
        link: "https://floradobrasil.jbrj.gov.br/consulta/?grupo=6&familia=null&genero=Erythrina&especie=velutina&autor=&nomeVernaculo=&nomeCompleto=&formaVida=null&substrato=null&ocorreBrasil=QUALQUER&ocorrencia=OCORRE&endemismo=TODOS&origem=TODOS&regiao=QUALQUER&ilhaOceanica=32767&estado=QUALQUER&domFitogeograficos=QUALQUER&vegetacao=TODOS&mostrarAte=SUBESP_VAR&opcoesBusca=TODOS_OS_NOMES&loginUsuario=Visitante&senhaUsuario=&contexto=consulta-publica&pagina=1#CondicaoTaxonCP",
    },
    {
        titulo: "Quixabeira - <i>Sideroxylon obtusifolium</i> (Roem. & Schult.) T.D.Penn.",
        descricao: "A quixabeira é amplamente utilizada na medicina popular por suas diversas propriedades terapêuticas. Suas raízes, casca, folhas e frutos são ricos em compostos bioativos que conferem à planta ações anti-inflamatória, analgésica, cicatrizante, antidiabética, hipocolesterolêmica, adstringente e tônica. Devido a essas propriedades, a quixabeira é utilizada para tratar diversas condições de saúde, como inflamações, dores, feridas, diabetes, colesterol alto, diarreia e para fortalecer o organismo. As formas de uso mais comuns são o chá, a decocção e as cápsulas. No entanto, é importante ressaltar que o uso da quixabeira deve ser feito com cautela e sob orientação médica, pois pode causar efeitos colaterais e interagir com outros medicamentos.</p><p>Chá da casca</p><p>Ferve-se 1 litro de água e adiciona-se cinco colheres de sopa de cascas secas. Abafe por 15 minutos. Coe o chá e adoce se desejar. Recomenda-se ingerir de 2 a 3 xícaras durante o dia, entre as refeições.</p>",
        link: "https://floradobrasil.jbrj.gov.br/consulta/?grupo=6&familia=null&genero=Sideroxylon&especie=obtusifolium&autor=&nomeVernaculo=&nomeCompleto=&formaVida=null&substrato=null&ocorreBrasil=QUALQUER&ocorrencia=OCORRE&endemismo=TODOS&origem=TODOS&regiao=QUALQUER&ilhaOceanica=32767&estado=QUALQUER&domFitogeograficos=QUALQUER&vegetacao=TODOS&mostrarAte=SUBESP_VAR&opcoesBusca=TODOS_OS_NOMES&loginUsuario=Visitante&senhaUsuario=&contexto=consulta-publica&pagina=1#CondicaoTaxonCP",
    },
];

